version: "3"
services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:80
    networks:
      - app-network
    environment:
      - VIRTUAL_HOST=app.loc
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:80
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - VIRTUAL_HOST=api.app.loc
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydatabase
    ports:
      - 3306:3306
    networks:
      - app-network

networks:
  app-network:
